---
- name: AWS Cloud Operations
  hosts: localhost
  connection: local

  vars:
    cidr_block: "10.0.0.0/16"
  tasks:
    - name: Create a vpc called myvpc
      amazon.aws.ec2_vpc_net:
        name: "myvpc"
        region: "us-east-1"
        cidr_block: "{{ cidr_block }}"
        dns_support: true
        tags:
          Description: Created by ansible
          Name: "myvpc"
      register: myvpc

    - name: Create a keypair called mykeypair
      amazon.aws.ec2_key:
        name: "mykeypair"
        region: "us-east-1"
      register: mykeypair

    - name: Create vpc_id variable from myvpc
      ansible.builtin.set_fact:
        vpc_id: "{{ myvpc.vpc.id }}"
      register: vpc_id

    - name: Create a security group called mysg and allow SSH, HTTP and HTTPS traffic
      amazon.aws.ec2_security_group:
        name: "mysg"
        region: "us-east-1"
        vpc_id: "{{ vpc_id }}"
        rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      register: mysg
